# Generated by Django 2.2.16 on 2020-12-14 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='エリア')),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='アトラクション')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Area', verbose_name='エリア'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='attraction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Attraction', verbose_name='アトラクション'),
            preserve_default=False,
        ),
    ]
