# Generated by Django 2.2.16 on 2020-12-10 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201210_2358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category2',
        ),
    ]
