# Generated by Django 2.2.16 on 2020-12-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201214_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='area',
        ),
        migrations.RemoveField(
            model_name='post',
            name='attraction',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Attraction',
        ),
    ]
