# Generated by Django 2.2.16 on 2020-12-21 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_formpreviewtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormPreviewTest',
        ),
    ]
