# Generated by Django 2.2 on 2021-01-16 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210116_1500'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
