# Generated by Django 2.2 on 2021-01-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='ProfImage画像')),
            ],
        ),
    ]
