# Generated by Django 2.2 on 2021-01-17 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_profimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfImage',
        ),
    ]
