# Generated by Django 2.2 on 2021-01-17 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_profimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='prof_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.ProfImage'),
            preserve_default=False,
        ),
    ]
