# Generated by Django 2.2 on 2021-01-18 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_delete_profimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='area',
        ),
        migrations.RemoveField(
            model_name='post',
            name='attraction',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Attraction',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
