# Generated by Django 2.2 on 2021-01-20 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210119_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='area',
        ),
    ]
