# Generated by Django 2.2 on 2021-01-22 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
