# Generated by Django 2.2 on 2021-02-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='slug',
            field=models.SlugField(default=1, verbose_name='スラッグ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attraction',
            name='slug',
            field=models.SlugField(default=1, verbose_name='スラッグ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, verbose_name='スラッグ'),
            preserve_default=False,
        ),
    ]
