# Generated by Django 2.2 on 2021-05-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210220_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='public',
            field=models.IntegerField(default=False, verbose_name='公開フラグ'),
        ),
    ]
