# Generated by Django 2.2 on 2021-01-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210118_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='アイコン'),
        ),
    ]
