# Generated by Django 2.2 on 2021-01-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210124_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ニックネーム'),
        ),
    ]
